---
kind: pipeline
type: docker
name: build-amd64

platform: { os: linux, arch: amd64 }

steps:
- name: prepare
  image: plugins/docker
  settings:
    dry_run: true
    repo: build/dweomer/what
    target: build
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: build
  pull: never
  image: build/dweomer/what
  commands:
  - make ci
  environment:
    DOCKER_BUILDKIT: "1"
    GOARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    checksum: [ "sha256" ]
    checksum_file: "CHECKSUMsum-${DRONE_STAGE_ARCH}.txt"
    checksum_flatten: true
    files: dist/artifacts/*
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: publish
  image: plugins/docker
  settings:
    build_args:
      GOARCH: "${DRONE_STAGE_ARCH}"
    password:
      from_secret: docker_password
    repo: dweomer/what
    tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
    target: package
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: build-arm64

platform: { os: linux, arch: arm64 }

steps:
- name: prepare
  image: plugins/docker
  settings:
    dry_run: true
    repo: build/dweomer/what
    target: build
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: build
  pull: never
  image: build/dweomer/what
  commands:
  - make ci
  environment:
    DOCKER_BUILDKIT: "1"
    GOARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    checksum: [ "sha256" ]
    checksum_file: "CHECKSUMsum-${DRONE_STAGE_ARCH}.txt"
    checksum_flatten: true
    files: dist/artifacts/*
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: publish
  image: plugins/docker
  settings:
    target: package
    build_args:
      GOARCH: "${DRONE_STAGE_ARCH}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dweomer/what
    tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: build-armhf

platform: { os: linux, arch: arm }

steps:
- name: prepare
  image: plugins/docker
  settings:
    dry_run: true
    repo: build/dweomer/what
    target: build
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: build
  pull: never
  image: build/dweomer/what
  commands:
  - make ci
  environment:
    DOCKER_BUILDKIT: "1"
    GOARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    checksum: [ "sha256" ]
    checksum_file: "CHECKSUMsum-${DRONE_STAGE_ARCH}.txt"
    checksum_flatten: true
    files: dist/artifacts/*
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: publish
  image: plugins/docker
  settings:
    build_args:
      GOARCH: "${DRONE_STAGE_ARCH}"
    password:
      from_secret: docker_password
    repo: dweomer/what
    tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
    target: package
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: manifest

platform: { os: linux, arch: amd64 }

steps:
- name: publish-manifest
  image: plugins/manifest
  settings:
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
    target: "dweomer/what:${DRONE_TAG}"
    template: "dweomer/what:${DRONE_TAG}-ARCH"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

depends_on:
- build-amd64
- build-arm64
- build-armhf

...
