---
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: plugins/docker
  settings:
    target: build
    repo: build/dweomer/what
    dry_run: true
  volumes:
    - name: docker
      path: /var/run/docker.sock

- name: build
  image: build/dweomer/what
  pull: never
  commands:
    - make ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    files: dist/artifacts/*
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: publish
  image: plugins/docker
  settings:
    target: package
    repo: dweomer/what
    tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: prepare
    image: plugins/docker
    settings:
      target: build
      repo: build/dweomer/what
      dry_run: true
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build
    image: build/dweomer/what
    pull: never
    commands:
      - make ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: dist/artifacts/*
    when:
      event:
        - tag
      instance:
        - drone-publish.k3s.io
      ref:
        - refs/head/master
        - refs/tags/*

  - name: publish
    image: plugins/docker
    settings:
      target: package
      repo: dweomer/what
      tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      instance:
        - drone-publish.k3s.io
      ref:
        - refs/head/master
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: build-armhf

platform:
  os: linux
  arch: arm

steps:
  - name: prepare
    image: plugins/docker
    settings:
      target: build
      repo: build/dweomer/what
      dry_run: true
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build
    image: build/dweomer/what
    pull: never
    commands:
      - make ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: dist/artifacts/*
    when:
      event:
        - tag
      instance:
        - drone-publish.k3s.io
      ref:
        - refs/head/master
        - refs/tags/*

  - name: publish
    image: plugins/docker
    settings:
      target: package
      repo: dweomer/what
      tag: "${DRONE_TAG}-${DRONE_STAGE_ARCH}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      instance:
        - drone-publish.k3s.io
      ref:
        - refs/head/master
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: publish-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
    target: "dweomer/what:${DRONE_TAG}"
    template: "dweomer/what:${DRONE_TAG}-ARCH"
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

depends_on:
- build-amd64
- build-arm64
- build-armhf

...
